# Generated by Django 4.2 on 2023-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(default='Morern', max_length=255),
            preserve_default=False,
        ),
    ]
