# Generated by Django 4.2 on 2023-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(default='friendly name', max_length=255),
            preserve_default=False,
        ),
    ]
